export const REQUEST_URL = 'http://localhost:52000/rest'
export const LOGIN = REQUEST_URL + '/user/login'
export const GET_PROJECTS = REQUEST_URL + '/project/query'
export const CREATE_PROJECT = REQUEST_URL + '/project/create'
export const MODIFY_PROJECT = REQUEST_URL + '/project/modify'
